repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b" # v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
  - repo: https://github.com/psf/black
    rev: "8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b" # 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: "c8ab4a5b21bac924d106e3103dd7c979fdd0f9bc" # 6.0.1
    hooks:
      - id: isort
        args: [--profile=black]
  - repo: https://github.com/PyCQA/flake8
    rev: "16f5f28a384f0781bebb37a08aa45e65b9526c50" # 7.2.0
    hooks:
      - id: flake8
        # ignore E203 for whitespace around ':' issues

        # see https://github.com/PyCQA/pycodestyle/issues/373
        # ignore W503 due to how black formats (related is W504)
        args: [--max-line-length=88, "--ignore=E203,W503"]
